FROM postgres:10
WORKDIR /var/lib/postgresql
COPY ./docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
VOLUME ["/var/lib/postgresql/data"]
ENV POSTGRES_USER point
ENV POSTGRES_PASSWORD point
ENV POSTGRES_DB point
EXPOSE 5432
